language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_script:
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - echo "twitterConsumerKey=$TWITTER_CONSUMER_KEY" >> samples/app/fabric.properties
    - echo "twitterConsumerSecret=$TWITTER_CONSUMER_SECRET" >> samples/app/fabric.properties
    - echo "apiKey=$API_KEY" >> samples/app/fabric.properties
    - echo "apiSecret=$API_SECRET" >> samples/app/fabric.properties
    - ./gradlew assemble test connectedCheck --parallel
